# Generated by Django 2.1.5 on 2020-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Автор', max_length=255),
            preserve_default=False,
        ),
    ]
